name:    aulahaskell
version: "0.0.0"

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base 

# version 1.0 had a bug in reexporting Handler, causing trouble
- classy-prelude-yesod 

- yesod 
- yesod-core
- yesod-auth
- yesod-static 
- yesod-form 
- bytestring 
- text
- persistent 
- persistent-postgresql 
- template-haskell
- shakespeare
- monad-control 
- wai-extra 
- yaml 
- http-conduit 
- directory 
- warp 
- data-default
- aeson
- conduit 
- monad-logger 
- fast-logger 
- wai-logger 
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- http-types
- foreign-store

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  aulahaskell:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aulahaskell
    when:
    - condition: flag(library-only)
      buildable: false

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
